id: P000550
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG6134
  title: འཛམ་གླིང་གནའ་རབས་ལོ་རྒྱུས་ཀྱི་གཏམ་རྒྱུད།
  author: ''
  volumes:
    66ca4f01418b4b669ef14db9380aeb52:
      image_group_id: I1KG8441
      title: Volume 1 of 'dzam gling gna' rabs lo rgyus kyi gtam rgyud/
      volume_number: 1
      total_pages: 432
      base_file: v001.txt
